services:
  db:
    image: mysql
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=fSM3A-8HC2Tb
    expose:
      - 3306
    volumes:
      - /home/ubuntu/prod/db:/var/lib/mysql
nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
      #- 4711:80
    volumes:
    - /home/ubuntu/prod/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro


  flask:
    image: msagace/rentalcars:latest
      #image: snickch/flask001:v2
      #image: microblog_v11
    container_name: flask
    restart: always
    expose:
      - 5000
    #volumes:
    #  - /home/ubuntu/prod/app/:/app:rw
    #command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - "db"
