"""empty message

Revision ID: d7c864a4908d
Revises: 2c88e43a9cdd
Create Date: 2022-08-28 13:58:33.537891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c864a4908d'
down_revision = '2c88e43a9cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('telephone', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=True)
    op.create_index(op.f('ix_user_telephone'), 'user', ['telephone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telephone'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'telephone')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
