"""empty message

Revision ID: d99379e8c882
Revises: 0ff77410ff09
Create Date: 2022-08-27 11:14:51.883337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99379e8c882'
down_revision = '0ff77410ff09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('reserved_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reserved_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('period')
    # ### end Alembic commands ###
